Healthdata:
    type: object
    config:
        fields:
            healthDataUUID:
                type: "ID!"
            patientUUID:
                type: "ID!"
            callTimeStarts:
                type: "DateTime"
            callTimeEnds:
                type: "DateTime"
            dateTimeCollected:
                type: "DateTime"
            weight:
                type: "Int"
            height:
                type: "Int"
            bloodPressureHigh:
                type: "Int"
            bloodPressureLow:
                type: "Int"
            glucoseLevel:
                type: "Int"