Query:
    type: object
    config:
        description: 'Just one query'
        fields:
            allHealthData:
                type: '[Healthdata]'
                resolve: "@=resolver('all_healthdata', [args])"
